#ifndef __STRID_H__
#define __STRID_H__
enum strid_lang
{
STRING_ID_NULL,/* 空 */
STRING_ID_OK,  /* 正确 */
STRING_ID_FAIL,/* 错误 */
STRING_ID_BAD_REQUEST,
STRING_ID_NOT_LOGIN,
STRING_ID_LOGIN_ERROR,
STRING_ID_USER_EXIST,
STRING_ID_USER_NOT_EXIST,
STRING_ID_PASSWORD_ERROR,
STRING_ID_CHANGE_OTHER_PASS,
STRING_ID_NO_ENOUGH_MEMORY,
STRING_ID_NO_PERMISSION,
STRING_ID_INVILID_OPERATION,
STRING_ID_READ_CONFIG_ERROR,
STRING_ID_SERVER_INTERNAL_ERROR,
STRING_ID_CODEC,
STRING_ID_TRIGGER,
STRING_ID_NETWORK,
STRING_ID_PTZ,
STRING_ID_RS485,
STRING_ID_SYSTEM,
STRING_ID_CONTROL,
STRING_ID_FTP,
STRING_ID_SMTP,
STRING_ID_NTP,
STRING_ID_ALARMPORT,
STRING_ID_SECURITY,
STRING_ID_ANALYTICS,
STRING_ID_RECORDER,
STRING_ID_JPEG,
STRING_LT_UNKNOW,
STRING_LT_ALARM_UNKNOW,
STRING_LT_ALARM_IN                ,          /* 外部报警输入 */
STRING_LT_ALARM_OUT               ,           
STRING_LT_ALARM_IN_STOP           ,          /* 外部告警输入结束 */
STRING_LT_MOTION_DETECTIVE        ,
STRING_LT_MOTION_LOST             ,
STRING_LT_EXP_UNKNOW              ,          /* 未知异常类型 */ 
STRING_LT_EXP_VIDEO_LOST          ,          /* 视频丢失 */
STRING_LT_EXP_ILLEGAL_ACCESS      ,          /* 非法访问 */
STRING_LT_EXP_HDD_FULL            ,          /* 硬盘满 */
STRING_LT_EXP_HDD_ERROR           ,          /* 硬盘出错 */
STRING_LT_EXP_SENSOR_RESET        ,          /* 图像传感器复位 */
STRING_LT_EXP_IP_CONFLICT         ,          /* IP 冲突 */
STRING_LT_EXP_NET_BROKEN          ,          /* 网络断开 */
STRING_LT_EXP_VIDEO_COMEBACK      ,          /* 视频恢复 */
STRING_LT_OPT_UNKNOW,
STRING_LT_OPT_DVR_START,
STRING_LT_OPT_DVR_STOP,
STRING_LT_OPT_ILLEGAL_STOP,
STRING_LT_OPT_RESTORE_DEFAULT,
STRING_LT_OPT_REMOTE_LOGIN,
STRING_LT_OPT_REMOTE_LOGOUT,
STRING_LT_OPT_REMOTE_START_REC,
STRING_LT_OPT_REMOTE_STOP_REC,
STRING_LT_OPT_REMOTE_REBOOT_SYS,
STRING_LT_OPT_REMOTE_REBOOT_APP,
STRING_LT_OPT_REMOTE_GET_PARA,
STRING_LT_OPT_REMOTE_SET_PARA,
STRING_LT_OPT_REMOTE_GET_STATUS,
STRING_LT_OPT_REMOTE_ALARM,
STRING_LT_OPT_REMOTE_DISABLE_ALM,
STRING_LT_OPT_REMOTE_QUERY_LOG,
STRING_LT_OPT_REMOTE_DOWNLOAD_LOG,
STRING_LT_OPT_REMOTE_TALK_START,
STRING_LT_OPT_REMOTE_TALK_STOP,
STRING_LT_OPT_REMOTE_UPGRADE,
STRING_LT_OPT_REMOTE_QUERY_DATA,
STRING_LT_OPT_REMOTE_DOWNLAOD,
STRING_LT_OPT_REMOTE_PTZCTRL,
STRING_LT_OPT_REMOTE_START_MON,
STRING_LT_OPT_REMOTE_STOP_MON,
STRING_LT_OPT_REMOTE_ADD_USER,
STRING_LT_OPT_REMOTE_DEL_USER,
STRING_LT_OPT_REMOTE_QUERY_USER,
STRING_LT_OPT_REMOTE_CHPASS_USER,
STRING_LT_OPT_REMOTE_SET_TIME,
STRING_LT_OPT_NETWORK_UPDATE,
STRING_ID_MANUAL,
STRING_ID_DHCP,
STRING_ID_PPPOE,
STRING_ID_DDNS,
STRING_ID_JEPG_EMAIL_SUBJECT,
STRING_ID_JEPG_EMAIL_CONTENT,
STRING_ID_REBOOT_MANUAL,
STRING_ID_REBOOT_AUTO,
STRING_ID_REBOOT_EXP,
STRING_ID_SENSOR,
STRING_ID_AUDIO,
STRING_LT_EXP_CODEC_DEAD      ,          /* 编码器异常 */
STRING_LT_EXP_HDD_INDEX_OVER  ,          /* 录像文件索引数超限 */
STRING_TOTAL_NUMBER,     //STRID的计数值，必须放在最后一行，没有字符串与其对应

};
#endif
